### ISSUE TITLE
trying to get season 3 to run - regular expression error

### ISSUE THREAD

**Issue by tlawork** [wcandillon/can-it-be-done-in-react-native#152]
I have expo installed and android studio and i can get expo init new projects to run, but I can not make season 3 run. it gives the following error below.  I am not that experienced with expo - am I doing something wrong?

yarn run v1.22.5
$ expo start
Starting project at C:\Users\tlind\Documents\PLC\can-it-be-done-in-react-native\season3
Developer tools running on http://localhost:19002
Opening developer tools in the browser...
error Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class.

SyntaxError: Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class
    at new RegExp (<anonymous>)
    at blacklist (C:\Users\tlind\Documents\PLC\can-it-be-done-in-react-native\season3\node_modules\metro-config\src\defaults\blacklist.js:34:10)
    at getBlacklistRE (C:\Users\tlind\Documents\PLC\can-it-be-done-in-react-native\season3\node_modules\@react-native-community\cli\build\tools\loadMetroConfig.js:66:59)
    at getDefaultConfig (C:\Users\tlind\Documents\PLC\can-it-be-done-in-react-native\season3\node_modules\@react-native-community\cli\build\tools\loadMetroConfig.js:82:20)
    at load (C:\Users\tlind\Documents\PLC\can-it-be-done-in-react-native\season3\node_modules\@react-native-community\cli\build\tools\loadMetroConfig.js:118:25)
    at Object.runServer [as func] (C:\Users\tlind\Documents\PLC\can-it-be-done-in-react-native\season3\node_modules\@react-native-community\cli\build\commands\server\runServer.js:82:58)
    at Command.handleAction (C:\Users\tlind\Documents\PLC\can-it-be-done-in-react-native\season3\node_modules\@react-native-community\cli\build\index.js:164:23)
    at Command.listener (C:\Users\tlind\Documents\PLC\can-it-be-done-in-react-native\season3\node_modules\commander\index.js:315:8)
    at Command.emit (events.js:315:20)
    at Command.parseArgs (C:\Users\tlind\Documents\PLC\can-it-be-done-in-react-native\season3\node_modules\commander\index.js:651:12)
Metro Bundler process exited with code 1
Error: Metro Bundler process exited with code 1
    at ChildProcess.<anonymous> (C:\@expo\xdl@59.0.25\src\start\startLegacyReactNativeServerAsync.ts:269:16)
    at Object.onceWrapper (events.js:422:26)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

C:\Users\tlind\Documents\PLC\can-it-be-done-in-react-native\season3>

**Comment by tlawork** [comment]
self update - I used NPM instead of yarn - then it was missing react-native-screens - but then I was able to get it to work using NPM instead of yarn.  I will let you close this out if that is expected.  Otherwise yarn configuration probably needs a look.
